image: golang:latest

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - test
  - acceptance_test

before_script:

go_build:
  stage: build
  script:
    - go build ./...
  artifacts:
    paths:
      - .

unit_test:
  stage: test
  script:
    - go install github.com/onsi/ginkgo/ginkgo
    - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress --skip="Stress"
    - go test -coverprofile=cover.out ./...
    - go tool cover -func=cover.out

cache_acceptance_test:
  stage: acceptance_test
  script:
    - go install github.com/onsi/ginkgo/ginkgo
    - cd timing/caches/acceptancetest
    - go build
    - ./acceptancetest

new_cache_aceptance_test:
  stage: acceptance_test
  script:
    - cd timing/newcaches/l1v/acceptancetest
    - go build
    - ./acceptancetest

acceptance_test:
  stage: acceptance_test
  tags:
    - multi_core
  script:
    - apt-get update -qq && apt-get install -y -qq python3
    - python3 acceptance_test.py
